services:
  directus:
    image: directus/directus
    restart: always
    environment:
      - DB_CLIENT=sqlite3
      - DB_FILENAME=/directus/database/database.sqlite
      - STORAGE_LOCAL_ROOT=/directus/uploads
      - NODE_VERSION=16.18.1
      - KEY=yBvPLfmFZoe9bT3gV29VfN
      - SECRET=AcsbBGZ8MppPTUPwpGb7YP
    ports:
      - "8055:8055"
    volumes:
      - ./directus/database:/directus/database
      - ./directus/uploads:/directus/uploads
    networks:
      - main
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - HOST=0.0.0.0
      - DIRECTUS_URL=http://directus:8055
      - DIRECTUS_SECRET=6JrVkVDBwRh-9bk8b8FtbFWPRA4XaJJ2
    volumes:
      - ./build:/build
    networks:
      - main
networks:
  main:
    driver: bridge