// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'de-DE'

export type Locales =
	| 'de-DE'
	| 'en-US'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	nav: {
		/**
		 * Home
		 */
		home: string
		/**
		 * Verein
		 */
		association: string
		/**
		 * Engagement
		 */
		engagement: string
		/**
		 * Förderung
		 */
		funding: string
		/**
		 * News
		 */
		news: string
		/**
		 * Konferenzen
		 */
		conferences: string
	}
	/**
	 * Deutsche Model United Nations e.V.
	 */
	title: string
	/**
	 * Impressum & Datenschutz
	 */
	imprint: string
}

export type TranslationFunctions = {
	nav: {
		/**
		 * Home
		 */
		home: () => LocalizedString
		/**
		 * Verein
		 */
		association: () => LocalizedString
		/**
		 * Engagement
		 */
		engagement: () => LocalizedString
		/**
		 * Förderung
		 */
		funding: () => LocalizedString
		/**
		 * News
		 */
		news: () => LocalizedString
		/**
		 * Konferenzen
		 */
		conferences: () => LocalizedString
	}
	/**
	 * Deutsche Model United Nations e.V.
	 */
	title: () => LocalizedString
	/**
	 * Impressum & Datenschutz
	 */
	imprint: () => LocalizedString
}

export type Formatters = {}
