// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'de-DE'

export type Locales =
	| 'de-DE'
	| 'en-US'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	nav: {
		/**
		 * Home
		 */
		home: string
		/**
		 * Verein
		 */
		association: string
		/**
		 * Engagement
		 */
		engagement: string
		/**
		 * Förderung
		 */
		funding: string
		/**
		 * News
		 */
		news: string
		/**
		 * Konferenzen
		 */
		conferences: string
	}
	home: {
		/**
		 * Der Verein
		 */
		association: string
		/**
		 * Konferenzen
		 */
		conferences: string
		section1: {
			/**
			 * Politisches Handeln durch politische Bildung
			 */
			heading: string
			/**
			 * das ist unser Ziel bei Deutsche Model United Nations (DMUN) e.V. Wir sind ein gemeinnütziger Verein aus jungen Erwachsenen, die sich für internationale Politik und die Vereinten Nationen begeistern. Wir sind bundesweit und auf internationaler Ebene im Bereich der politischen Jugendbildung und des Youth Empowerments tätig. 2003 gegründet, und seit 2012 als Nichtregierungsorganisation mit speziellem Beraterstatus beim Wirtschafts- und Sozialrat der Vereinten Nationen sowie beim UNDPI akkreditiert, veranstalten wir politische Planspiele, bei denen Jugendliche und junge Erwachsene zwischen 15 und 21 Jahren eine Konferenz der Vereinten Nationen simulieren. Außerdem setzen wir uns auf internationaler Ebene für politische Jugendbildung und die Partizipation junger Menschen an politischen Prozessen ein.
			 */
			paragraph: string
		}
	}
	/**
	 * Deutsche Model United Nations e.V.
	 */
	title: string
	/**
	 * Impressum & Datenschutz
	 */
	imprint: string
}

export type TranslationFunctions = {
	nav: {
		/**
		 * Home
		 */
		home: () => LocalizedString
		/**
		 * Verein
		 */
		association: () => LocalizedString
		/**
		 * Engagement
		 */
		engagement: () => LocalizedString
		/**
		 * Förderung
		 */
		funding: () => LocalizedString
		/**
		 * News
		 */
		news: () => LocalizedString
		/**
		 * Konferenzen
		 */
		conferences: () => LocalizedString
	}
	home: {
		/**
		 * Der Verein
		 */
		association: () => LocalizedString
		/**
		 * Konferenzen
		 */
		conferences: () => LocalizedString
		section1: {
			/**
			 * Politisches Handeln durch politische Bildung
			 */
			heading: () => LocalizedString
			/**
			 * das ist unser Ziel bei Deutsche Model United Nations (DMUN) e.V. Wir sind ein gemeinnütziger Verein aus jungen Erwachsenen, die sich für internationale Politik und die Vereinten Nationen begeistern. Wir sind bundesweit und auf internationaler Ebene im Bereich der politischen Jugendbildung und des Youth Empowerments tätig. 2003 gegründet, und seit 2012 als Nichtregierungsorganisation mit speziellem Beraterstatus beim Wirtschafts- und Sozialrat der Vereinten Nationen sowie beim UNDPI akkreditiert, veranstalten wir politische Planspiele, bei denen Jugendliche und junge Erwachsene zwischen 15 und 21 Jahren eine Konferenz der Vereinten Nationen simulieren. Außerdem setzen wir uns auf internationaler Ebene für politische Jugendbildung und die Partizipation junger Menschen an politischen Prozessen ein.
			 */
			paragraph: () => LocalizedString
		}
	}
	/**
	 * Deutsche Model United Nations e.V.
	 */
	title: () => LocalizedString
	/**
	 * Impressum & Datenschutz
	 */
	imprint: () => LocalizedString
}

export type Formatters = {}
