// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'de'
	| 'en'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * Deutsche Model United Nations e.V. – Official website
	 */
	title: string
	/**
	 * this is a test
	 */
	test: string
}

export type TranslationFunctions = {
	/**
	 * Deutsche Model United Nations e.V. – Official website
	 */
	title: () => LocalizedString
	/**
	 * this is a test
	 */
	test: () => LocalizedString
}

export type Formatters = {}
